export const state = {
  session: null,
  data: null,
  error: "",
  pushStatus: null,
  admin: null,
  passwordResetLink: null,
  notificationsData: null,
  notificationFreshIds: new Set(),
  debug: null,
  pollTimer: null,
  polling: false,
  deferredRender: false,
  realtime: null,
  realtimeRefreshTimer: null,
  view: "home",
  homeTab: "friends",
  achievementTab: "individual",
  adminTab: "overview",
  adminAchievementSlug: "",
  historyFriendId: null,
  historyData: null,
  profileUserId: null,
  profileData: null,
  profileError: "",
  profileNotice: "",
  settingsError: "",
  settingsNotice: "",
  woodKeyboardOpen: false,
  toast: "",
  showNotificationSheet: false,
  showAddSheet: false,
  addError: "",
  showGroupSheet: false,
  showGroupInviteSheet: false,
  groupInviteGroupId: null,
  groupError: "",
  showBugReportSheet: false,
  bugReportText: "",
};

export const swipeOpen = new Set();
