export const state = {
  session: null,
  data: null,
  error: "",
  pushStatus: null,
  admin: null,
  debug: null,
  pollTimer: null,
  polling: false,
  realtime: null,
  realtimeRefreshTimer: null,
  view: "home",
  homeTab: "friends",
  adminTab: "overview",
  historyFriendId: null,
  historyData: null,
  profileUserId: null,
  profileData: null,
  profileError: "",
  profileNotice: "",
  settingsError: "",
  woodKeyboardOpen: false,
  toast: "",
  showAddSheet: false,
  addError: "",
  showGroupSheet: false,
  groupError: "",
};

export const swipeOpen = new Set();
