export const WOOD_NOTIFICATION_STYLES = [
  {
    id: "classic",
    icon: "/notifications/wood-classic.png",
  },
  {
    id: "mail",
    icon: "/notifications/wood-mail.png",
  },
  {
    id: "alert",
    icon: "/notifications/wood-alert.png",
    vibrate: [80, 35, 120],
  },
  {
    id: "long",
    icon: "/notifications/wood-long.png",
  },
  {
    id: "summon",
    icon: "/notifications/wood-summon.png",
    vibrate: [40, 30, 40, 30, 120],
  },
];

export const WOOD_NOTIFICATION_TITLES = [
  "Wood",
  "{wood}",
  "Incoming Wood",
  "You got Wood",
  "You've got Wood",
  "Knock knock",
  "Wood delivery",
  "A Wood appears",
  "Fresh Wood",
  "Premium Wood",
  "Certified Wood",
  "Emergency Wood",
  "Wood alert",
  "Wood detected",
  "Wood acquired",
  "Wood unlocked",
  "Wood incoming",
  "New Wood just dropped",
  "The Wood is here",
  "Behold: Wood",
  "Wood o'clock",
  "Wood report",
  "Wood bulletin",
  "Wood news",
  "Wood update",
  "Wood business",
  "Wood logistics",
  "Wood protocol",
  "Wood mode",
  "Wood status",
  "Wood signal",
  "Wood ping",
  "Wood request",
  "Wood receipt",
  "Wood confirmed",
  "Wood deployed",
  "Wood engaged",
  "Wood has landed",
  "Wood has arrived",
  "Wood from {sender}",
  "{sender} sent Wood",
  "{sender} did a Wood",
  "{sender} says Wood",
  "{sender} has Wood",
  "Message from {sender}",
  "A note from {sender}",
  "The Woodening",
  "Wood: Reloaded",
  "Return of the Wood",
  "The Wood Awakens",
  "Wood Hard",
  "Jurassic Wood",
  "The Big Woodowski",
  "Lord of the Woods",
  "Raiders of the Lost Wood",
  "Wood Actually",
  "Mission: Woodpossible",
  "The Wood Knight",
  "Wood Trek",
  "Wood Wars",
  "Wood Club",
  "Wood Fiction",
  "Wood Runner",
  "Wood Max",
  "Top Wood",
  "Woodzilla",
  "Wood Kong",
  "Woodbusters",
  "The Woodfather",
  "Woodfellas",
  "Wood Story",
  "The Wizard of Wood",
  "Gone with the Wood",
  "Wood Side Story",
  "The Sound of Wood",
  "Wood in Translation",
  "No Country for Old Wood",
  "There Will Be Wood",
  "Wood of Wall Street",
  "Mad Max: Fury Wood",
  "Wood Panther",
  "The Wood Ultimatum",
  "Forrest Stump",
  "The Wood Matrix",
  "Woodception",
  "The Wood Prestige",
];

export const WOOD_NOTIFICATION_BODIES = [
  "{sender} wooded you",
  "{sender} sent you {wood}",
  "{sender} sent Wood",
  "{sender} has sent Wood",
  "{sender} pressed the Wood button",
  "{sender} delivered the Wood",
  "{sender} has entered the Wood",
  "{sender} would like to talk about Wood",
  "{sender} says: Wood",
  "{sender}: Wood?",
  "{sender} did a Wood",
  "{sender} made a Wood happen",
  "{sender} launched a Wood",
  "{sender} deployed Wood",
  "{sender} submitted Wood",
  "{sender} shipped Wood",
  "{sender} posted Wood",
  "{sender} logged Wood",
  "{sender} filed a Wood",
  "{sender} opened the Wood portal",
  "{sender} has chosen Wood",
  "{sender} is thinking about Wood",
  "{sender} is outside with Wood",
  "{sender} has a Wood for you",
  "{sender} brought snacks. And Wood.",
  "{sender} sent the good Wood",
  "{sender} sent the important Wood",
  "{sender} sent one fresh {wood}",
  "{sender} sent locally sourced Wood",
  "{sender} sent artisanal Wood",
  "{sender} sent free-range Wood",
  "{sender} sent gluten-free Wood",
  "{sender} sent organic Wood",
  "{sender} sent emergency Wood",
  "{sender} sent forbidden Wood",
  "{sender} sent mysterious Wood",
  "{sender} sent suspiciously specific Wood",
  "{sender} sent emotionally available Wood",
  "{sender} sent a single Wood",
  "{sender} sent exactly one Wood",
  "{sender} sent Wood. That's the app.",
  "You got Wood",
  "You've got Wood",
  "Wood.",
  "Wood!",
  "Wood?",
  "Wood acquired.",
  "Wood received.",
  "Wood confirmed.",
  "Wood accepted.",
  "Wood detected.",
  "Wood unlocked.",
  "Wood deployed.",
  "Wood achieved.",
  "Wood has arrived.",
  "Wood has landed.",
  "Wood is happening.",
  "Wood is upon us.",
  "Wood is calling.",
  "Wood wants a word.",
  "Wood would like your attention.",
  "Wood requests your presence.",
  "Wood has entered the chat.",
  "Wood just dropped.",
  "Wood, but make it push.",
  "Wood, respectfully.",
  "Wood, if true.",
  "Wood, apparently.",
  "Wood. Big if true.",
  "Wood. Huge if correct.",
  "Wood. No further notes.",
  "Wood. That's it. That's the message.",
  "This is not a drill. It is Wood.",
  "Look alive. Wood arrived.",
  "Important Wood delivery.",
  "A single Wood has been summoned.",
  "The Wood has been summoned.",
  "The Wood has been foretold.",
  "The Wood has chosen you.",
  "The Wood abides.",
  "The Wood must flow.",
  "The Wood is strong with this one.",
  "The Wood is out there.",
  "The truth is Wood there.",
  "May the Wood be with you.",
  "Use the Wood.",
  "These are not the Woods you seek.",
  "I am your Wood.",
  "Help me, Wood. You're my only hope.",
  "Do or do not. There is Wood.",
  "It's over. I have the Wood ground.",
  "One Wood to rule them all.",
  "You shall not pass... without Wood.",
  "Fly, you Woods.",
  "My precious Wood.",
  "Nobody tosses a Wood.",
  "I solemnly swear I am up to Wood.",
  "Yer a Wood, Harry.",
  "After all this time? Wood.",
  "Expecto Woodtronum.",
  "You're gonna need a bigger Wood.",
  "Life, uh, finds a Wood.",
  "Clever Wood.",
  "Hold onto your Woods.",
  "Welcome to Wood Park.",
  "Wood phone home.",
  "I'll be Wood.",
  "Hasta la Wood, baby.",
  "Come with me if you want Wood.",
  "Wood me up, Scotty.",
  "Set phasers to Wood.",
  "Live long and Wood.",
  "Resistance is Wood.",
  "Make it Wood.",
  "Winter is Wooding.",
  "You know nothing, Wood Snow.",
  "A Wood always pays its debts.",
  "Hold the Wood.",
  "I drink and I Wood things.",
  "The night is dark and full of Wood.",
  "That's no moon. That's Wood.",
  "Houston, we have Wood.",
  "To Wood, and beyond.",
  "There's no place like Wood.",
  "Here's looking at Wood, kid.",
  "Frankly, my dear, I give a Wood.",
  "I'm walking here, with Wood.",
  "Show me the Wood.",
  "You had me at Wood.",
  "You can't handle the Wood.",
  "Say hello to my little Wood.",
  "I'm the Wood of the world.",
  "Keep your friends close and your Wood closer.",
  "The first rule of Wood Club is Wood.",
  "I see Wood people.",
  "Why so Wood?",
  "Some Woods just want to watch the world burn.",
  "It's not who I am underneath. It's Wood.",
  "With great Wood comes great responsibility.",
  "I'm something of a Wood myself.",
  "Wood. James Wood.",
  "Shaken, not Wood.",
  "The name's Wood. Just Wood.",
  "No, Mr Bond. I expect you to Wood.",
  "Elementary, my dear Wood.",
  "The game is aWood.",
  "To Wood or not to Wood.",
  "Friends, Romans, countrymen, lend me your Wood.",
  "Et tu, Wood?",
  "A horse! A horse! My kingdom for Wood!",
  "All the world's a Wood.",
  "Once more unto the Wood.",
  "Something Wood this way comes.",
  "The course of true Wood never did run smooth.",
  "It was the best of Woods.",
  "Please, sir, I want some Wood.",
  "Call me Woodmael.",
  "It is a truth universally acknowledged: Wood.",
  "Reader, I Wooded him.",
  "So it goes. Wood.",
  "Don't panic. Wood.",
  "Mostly harmless. Mostly Wood.",
  "The answer is 42 Woods.",
  "In the beginning, there was Wood.",
  "So long, and thanks for all the Wood.",
  "I have a dream. Of Wood.",
  "Ask not what Wood can do for you.",
  "One small Wood for a friend.",
  "That's one giant Wood for mankind.",
  "We choose to Wood.",
  "Give me Wood, or give me death.",
  "Four score and seven Woods ago.",
  "The only thing we have to fear is Wood itself.",
  "Speak softly and carry a big Wood.",
  "Float like a Wood, sting like a tree.",
  "I came. I saw. I Wooded.",
  "Veni. Vidi. Woodi.",
  "Carpe Wood.",
  "Wood, therefore I am.",
  "Cogito, ergo Wood.",
  "E = mcWood.",
  "Schrodinger's Wood has arrived.",
  "Newton's first law of Wood.",
  "For every action, an equal and opposite Wood.",
  "The mitochondria is the powerhouse of Wood.",
  "Wood is stored in the app.",
  "Wood.exe has stopped waiting.",
  "Loading Wood...",
  "Wood has joined your party.",
  "Achievement unlocked: Wood.",
  "Critical hit: Wood.",
  "It's dangerous to go alone. Take Wood.",
  "A wild Wood appeared.",
  "It's super Wood!",
  "Wood used Push Notification.",
  "Finish him. Woodality.",
  "All your Wood are belong to us.",
  "The cake is a Wood.",
  "Would you kindly accept this Wood?",
  "Praise the Wood.",
  "You died. But also: Wood.",
  "Get over here, Wood.",
  "Hadouken? More like Ha-wood-ken.",
  "Wood speed ahead.",
  "Wood me maybe.",
  "Never gonna give you Wood.",
  "Oops, all Wood.",
  "Live, laugh, Wood.",
  "Eat. Sleep. Wood. Repeat.",
  "Keep calm and Wood on.",
  "Wood happens.",
  "Big Wood energy.",
  "Tiny Wood, big feelings.",
  "Extremely normal Wood.",
  "Certified pre-owned Wood.",
  "Wood with no context.",
  "Contextless Wood arrived.",
  "Unsolicited Wood notification.",
  "Respectfully, Wood.",
  "As a treat: Wood.",
  "A little Wood, for morale.",
  "Wood for the group chat.",
  "Wood for your consideration.",
  "Wood has been placed on your desk.",
  "Please acknowledge receipt of Wood.",
  "The Wood committee has convened.",
  "Wood has passed peer review.",
  "Wood has cleared legal.",
  "Wood has entered production.",
  "Wood is now generally available.",
  "The Wood rollout begins now.",
  "Your Wood SLA has been breached.",
  "This Wood could have been an email.",
  "Per my last Wood.",
  "Circling back with Wood.",
  "Let's take this Wood offline.",
  "Quick sync: Wood.",
  "Action item: Wood.",
  "Low-lift Wood opportunity.",
  "High-impact Wood moment.",
  "Wood alignment requested.",
  "Can we double-click on Wood?",
  "Putting a pin in Wood.",
  "Wood is on the roadmap.",
  "Wood is out of scope, somehow.",
  "Wood shipped to prod.",
  "Wood passed CI.",
  "LGTM: Wood.",
  "Ship it. Wood.",
  "Works on my Wood.",
  "Cannot reproduce Wood.",
  "Expected behavior: Wood.",
  "Actual behavior: also Wood.",
  "Root cause: Wood.",
  "Postmortem: Wood happened.",
];

export const WOOD_NOTIFICATION_PRESETS = [
  {
    title: "You've got Wood",
    body: "{sender} sent the important stuff.",
  },
  {
    title: "Wood and prejudice",
    body: "It is a truth universally acknowledged: {sender} sent Wood.",
  },
  {
    title: "The Woodfather",
    body: "{sender} made you an offer you can tap.",
  },
  {
    title: "A New Wood",
    body: "{sender} sent Wood from a galaxy nearby.",
  },
  {
    title: "Wood Trek",
    body: "{sender} set phasers to Wood.",
  },
  {
    title: "Jurassic Wood",
    body: "{sender} spared no expense.",
  },
  {
    title: "The Big Woodowski",
    body: "The Wood abides. So does {sender}.",
  },
  {
    title: "Mission: Woodpossible",
    body: "{sender} chose to accept it.",
  },
  {
    title: "Wood Club",
    body: "First rule: {sender} sends Wood.",
  },
  {
    title: "The Wood Matrix",
    body: "{sender} offers the green button.",
  },
  {
    title: "Woodception",
    body: "{sender} sent Wood inside a push.",
  },
  {
    title: "Raiders of the Lost Wood",
    body: "{sender} found it and sent it.",
  },
  {
    title: "The Wood Knight",
    body: "{sender} rises.",
  },
  {
    title: "Wood Actually",
    body: "To me, you are Wood.",
  },
  {
    title: "There Will Be Wood",
    body: "{sender} drank your milkshake, then sent Wood.",
  },
  {
    title: "No Country for Old Wood",
    body: "{sender} flipped the coin.",
  },
  {
    title: "The Wood Ultimatum",
    body: "{sender} remembers everything.",
  },
  {
    title: "Forrest Stump",
    body: "{sender} says life is like a box of Wood.",
  },
  {
    title: "Gone with the Wood",
    body: "Frankly, {sender} sent a Wood.",
  },
  {
    title: "Wood Side Story",
    body: "{sender} feels pretty woody.",
  },
  {
    title: "The Sound of Wood",
    body: "The hills are alive with {sender}.",
  },
  {
    title: "Wood in Translation",
    body: "{sender} whispered Wood.",
  },
  {
    title: "Top Wood",
    body: "{sender} feels the need. The need for Wood.",
  },
  {
    title: "Woodbusters",
    body: "Who you gonna call? {sender}.",
  },
  {
    title: "The Wood Awakens",
    body: "{sender} felt a disturbance.",
  },
  {
    title: "Lord of the Woods",
    body: "One Wood to rule them all.",
  },
  {
    title: "Wood Potter",
    body: "{sender} solemnly swears they are up to Wood.",
  },
  {
    title: "Wood Park",
    body: "{sender} says life found a way.",
  },
  {
    title: "Wood Protocol",
    body: "{sender} initiated the only protocol.",
  },
  {
    title: "Push Fiction",
    body: "Say Wood again. {sender} dares you.",
  },
  {
    title: "Wood Alert",
    body: "This could have been an email from {sender}.",
  },
  {
    title: "WoodOps",
    body: "{sender} shipped Wood to prod.",
  },
  {
    title: "Standup Update",
    body: "Yesterday: Wood. Today: {sender}. Blockers: none.",
  },
  {
    title: "Per my last Wood",
    body: "{sender} is circling back.",
  },
  {
    title: "Action item",
    body: "Acknowledge {sender}'s Wood.",
  },
  {
    title: "Low-lift ask",
    body: "{sender} requests one Wood of alignment.",
  },
  {
    title: "Roadmap update",
    body: "Wood moved to now.",
  },
  {
    title: "CI passed",
    body: "{sender}'s Wood is green.",
  },
  {
    title: "LGTM",
    body: "Looks Good To Wood.",
  },
  {
    title: "Incident report",
    body: "Severity: Wood. Reporter: {sender}.",
  },
  {
    title: "Root cause",
    body: "{sender} pressed the button.",
  },
  {
    title: "Postmortem",
    body: "Wood happened. Lessons were learned.",
  },
  {
    title: "Scientific breakthrough",
    body: "For every tap, an equal and opposite Wood.",
  },
  {
    title: "Physics update",
    body: "E = mcWood.",
  },
  {
    title: "Philosophy update",
    body: "I Wood, therefore I am.",
  },
  {
    title: "Literature update",
    body: "It was the best of Woods.",
  },
  {
    title: "History update",
    body: "One small Wood from {sender}.",
  },
  {
    title: "Gaming moment",
    body: "A wild Wood appeared.",
  },
  {
    title: "Achievement unlocked",
    body: "{sender} sent Wood.",
  },
  {
    title: "Quest item acquired",
    body: "{wood} from {sender}.",
  },
  {
    title: "Critical hit",
    body: "{sender} used Wood. It's super effective.",
  },
  {
    title: "New drop",
    body: "{sender} found rare Wood.",
  },
  {
    title: "Patch notes",
    body: "Added Wood from {sender}.",
  },
  {
    title: "Loading complete",
    body: "Wood from {sender} is ready.",
  },
  {
    title: "Do not panic",
    body: "{sender} has sent mostly harmless Wood.",
  },
  {
    title: "Answer found",
    body: "It was Wood. Obviously.",
  },
  {
    title: "Forecast",
    body: "Cloudy with a chance of {sender}.",
  },
  {
    title: "Breaking Wood",
    body: "{sender} is the one who knocks.",
  },
  {
    title: "Wood call",
    body: "The call is coming from inside the app.",
  },
  {
    title: "Tiny ceremony",
    body: "Please rise for {sender}'s Wood.",
  },
  {
    title: "Official notice",
    body: "You have been Wooded.",
  },
  {
    title: "Wood invoice",
    body: "Amount due: one reply.",
  },
  {
    title: "Receipt",
    body: "Paid in full by {sender}.",
  },
  {
    title: "Return to sender",
    body: "Optional, but spiritually encouraged.",
  },
  {
    title: "A modest Wood",
    body: "{sender} sent one for morale.",
  },
  {
    title: "Pocket Wood",
    body: "{sender} had this lying around.",
  },
  {
    title: "Contextless Wood",
    body: "No notes from {sender}.",
  },
  {
    title: "Extremely normal",
    body: "{sender} sent a very standard Wood.",
  },
  {
    title: "Suspicious Wood",
    body: "{sender} knows what they did.",
  },
  {
    title: "Rare Wood",
    body: "A shiny one from {sender}.",
  },
  {
    title: "Wood Prime",
    body: "{sender} delivered same-day Wood.",
  },
  {
    title: "Wood Reserve",
    body: "{sender} opened the good stuff.",
  },
  {
    title: "Wood Classic",
    body: "Original flavor. Sent by {sender}.",
  },
  {
    title: "Wood Zero",
    body: "All the Wood, none of the context.",
  },
  {
    title: "Wood Max",
    body: "Bigger feelings. Same button.",
  },
  {
    title: "Wood Mini",
    body: "Small notification. Big Wood.",
  },
  {
    title: "Wood Pro",
    body: "{sender} unlocked advanced Wood.",
  },
  {
    title: "Wood Ultra",
    body: "The marketing team got involved.",
  },
];
